services:
  app:
    image: bellsoft/liberica-openjdk-alpine:11.0.16.1-1
    build:
      context: ./src/main/java
    command: javadoc -sourcepath ./src/main/java -cp ./out -d ./doc -subpackages ru
    volumes:
      - ./../../../src:/src
      - ./../../../doc:/doc

